config/routes.rb
Rails.application.routes.draw do
  get 'rankings/index'

  get 'rankings/show'

  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'admin_users/new'

  get 'users', to: 'users#index'
  get 'users/new'

  get 'towers', to: 'towers#index'

  get 'topics', to: 'topics#index'
  post 'topics/new', to: 'topics#create'
  post 'topics/show', to: 'zones#create'

  get 'questions/new'
  post 'questions/new', to: 'questions#create'

  get 'zones/show'

  get 'home', to: 'welcome#index'

  root 'sessions#new'

  resources :admin_users
  resources :zones
  resources :topics
  resources :towers
  resources :questions
  resources :rankings

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/tower.rb
class Tower < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/zone.rb
class Zone < ActiveRecord::Base
end

app/models/zones_question.rb
class ZonesQuestion < ActiveRecord::Base
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        @towers = Tower.all().order(id: :asc)
        @topics = Topic.all().order(id: :asc)
    end

    def new
        @tower = Tower.find(params[:tower_id])
    end

    def create
        @topic = Topic.new(topic_params)
        @topic.name = topic_params['name'].strip.downcase
        @topic.towers_id = topic_params['towers_id']

        if @topic.save!
            flash[:success] = "New tower added successfully!"
            redirect_to topics_path
        else
            flash[:error] = "Error!"
            @tower = Tower.find(params[:tower_id])
            render 'new'
        end
    end

    def show
        @topic = Topic.find(params[:id])
        @tower = Tower.find(@topic.towers_id)
        @zones = Zone.where(topics_id: @topic.id).order(difficulty: :asc)
        @zone = Zone.new
    end

    def edit
        @topic = Topic.find(params[:id])
    end

    def update
        @topic = Topic.find(params[:id])

        if @topic.update_attributes(topic_params)
            flash[:success] = "Edited Topic!"
            redirect_to topics_path
        else
            flash[:error] = "Error!"
            render 'edit'
        end
    end

    def destroy
        Topic.find(params[:id]).destroy
        flash[:success] = "Topic deleted"
        redirect_to topics_path
    end

    private
    def topic_params
        params.require(:topic).permit(:name, :towers_id)
    end
end

app/controllers/towers_controller.rb
class TowersController < ApplicationController
    def index
        @towers = Tower.all()
    end

    def new
        @tower = Tower.new
    end

    def create
        @tower = Tower.new(tower_params)
        @tower.name = tower_params['name'].strip.downcase

        if @tower.save!
            flash[:success] = "Tower added!"
            redirect_to towers_path
        else
            render 'new'
        end
    end

    def show
        @tower = Tower.find(params['id'])
    end

    def update
        tower = Tower.find(params['id'])
        tower.name = tower_params['name']

        if tower.save!
            flash[:success] = "Tower edited!"
            redirect_to towers_path
        else
            flash[:error] = "Error!"
            redirect_to towers_path
        end
    end

    def edit
        @tower = Tower.find(params[:id])
    end

    def destroy
        Tower.find(params[:id]).destroy
        flash[:success] = "Tower deleted!"
        redirect_to towers_path
    end

    private
    def tower_params
        params.require(:tower).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all()

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :logged_in_user, only: [:index]

    def index
    end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
    def show
        @zone = Zone.find(params['id'])
        @topic = Topic.find(@zone.topics_id)
        @tower = Tower.find(@topic.towers_id)

        @questions = Question.where(zones_id: params['id']).order(id: :asc)
        @count = 1
    end

    def new
    end

    def create
        @topic = Topic.find(zone_params['topic_id'])
        @tower = Tower.find(@topic.towers_id)

        @zone = Zone.new
        @zone.name = zone_params['name'].strip
        @zone.topics_id = zone_params['topic_id']
        @zone.difficulty = zone_params['difficulty']


        if @zone.save!
            flash[:success] = "New tower added successfully!"
            redirect_to topic_path(@topic.id)
        else
            flash[:error] = "Error!"
            redirect_to topic_path(@topic.id)
        end
    end

    def edit
        @zone = Zone.find(params[:id])
        @topic = Topic.find(params[:topic_id])
    end

    def update
         @zone = Zone.find(params[:id])

        if @zone.update_attributes(zone_params)
            flash[:success] = "Edited Zone!"
            redirect_to topic_path(zone_params[:topics_id])
        else
            flash[:error] = "Error!"
            render 'edit'
        end
    end

    def destroy
        topic_id = Zone.find(params[:id]).topic_id
        Zone.find(params[:id]).destroy
        flash[:success] = "Zone deleted"
        redirect_to topic_path(topic_id)
    end

    private
    def zone_params
        params.require(:zone).permit(:name, :difficulty, :topics_id)
    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
    def logged_in_user
        unless logged_in?
            flash[:danger] = "Please log in."
            redirect_to login_url
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
        content_for :title, page_title.to_s
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    # Returns the current logged-in user (if any).
    def current_user
        @current_user ||= AdminUser.find_by(id: session[:user_id])
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

      # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/topics/edit.html.erb
<% title "Topic" %>
<h1 class="text-center">Edit Topic</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @topic do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control'%>
            <br />
            <%= f.label :tower %>
            <br />
            <%= f.collection_select(:towers_id, Tower.all, :id, :name) %>
            <br />
            <br />
            <%= f.hidden_field :id, :value => @topic.id %>
            <%= f.submit "Edit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/topics/index.html.erb
<% @towers.each do |tower| %>
<table class = "table table-hover">
    <a id="<%= tower.name.split.join('_').downcase %>"></a>
    <h3 style="color:grey"><%= tower.name.upcase %></h3>    
         
    <thead>
        <tr>
            <th>
                Topic
                <a href="<%= topics_new_path(:tower_id => tower.id) %>" >
                    <button type = "button" class = "btn btn-default">add</button>
                </a>   
            </th>
            <th>Created at</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @topics.each do |topic| %>
        <% if topic.towers_id == tower.id %>
        <tr>
            <td><%= topic.name %></td>
            <td><%= topic.created_at %></td>
            <td>
                <a href="<%= topic_path(topic.id) %>" >
                    <button type="button" class="btn btn-success" aria-label="Left Align">
                        view
                    </button>
                </a>
                <a href="<%= edit_topic_path(topic.id) %>" >
                    <button type="button" class="btn btn-info" aria-label="Left Align">
                        edit
                    </button>
                </a>
                <%= link_to raw('<button type="button" class="btn btn-danger" aria-label="Left Align">delete</button>'), topic, method: :delete, data: { confirm: "You sure?" } %>
            </td>
        </tr>
        <% end %>
        <% end %>
    </tbody>
</table>
<% end %>

app/views/topics/new.html.erb
<% title "New Topic" %>
<h1 class="text-center"><%= @tower.name.upcase %></h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for :topic do |f| %>
            <label>New Topic Name</label>
            <%= f.text_field :name, class: 'form-control'%>
            <%= f.hidden_field :towers_id, :value => @tower.id %>
            <br />
            <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/topics/show.html.erb
<table class = "table table-hover">
    <ol class="breadcrumb">
        <li><a href="<%= towers_path %>"><%= @tower.name.upcase %></a></li>
        <li class="active"><%= @topic.name.capitalize %></li>
    </ol>
    <h1>Topic: <%= @topic.name.capitalize %></h1>
    <br />
    <h4>Zone List</h4>
    <thead>
        <tr>
            <th>Name</th>
            <th>Difficulty</th>
            <th>No. of Questions</th>
            <th>Created at</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @zones.each do |zone| %>
        <tr>
            <td><%= zone.name %></td>
            <td><%= zone.difficulty %></td>
            <td><%= Question.where(zones_id: zone.id).count %></td>
            <td><%= zone.created_at %></td>
            <td>
                <a href="<%= zone_path(zone.id) %>" >
                    <button type="button" class="btn btn-success" aria-label="Left Align">
                        view
                    </button>
                </a>
                <a href="<%= edit_zone_path(zone.id, topic_id: @topic.id) %>" >
                    <button type="button" class="btn btn-info" aria-label="Left Align">
                        edit
                    </button>
                </a>
                <%= link_to raw('<button type="button" class="btn btn-danger" aria-label="Left Align">delete</button>'), zone, method: :delete, data: { confirm: "You sure?" } %>
            </td>
        </tr>
        <% end %>
    </tbody>
   
</table>


<%= form_for @zone do |f| %>
<div class="row">
    <div class="col-md-3">
        <label>Zone Name</label>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="col-md-3">
        <label>Difficulty</label>
        <%= f.number_field :difficulty, class: 'form-control'%>
    </div>
    <%= f.hidden_field :topic_id, :value => @topic.id %>
</div>
<br />
<%= f.submit "Add", class: "btn btn-info" %>
<% end %>

app/views/towers/edit.html.erb
<% title "New Tower" %>
<h1 class="text-center">New Tower</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @tower do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control'%>
            <br />
            <%= f.hidden_field :id, :value => @tower.id %>
            <%= f.submit "Edit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/towers/index.html.erb
<table class = "table table-hover">
    <h2>Tower List</h2>
   
    <thead>
        <tr>
            <th>Name</th>
            <th>Created at</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @towers.each do |tower| %>
        <tr>
            <td><%= tower.name.upcase %></td>
            <td><%= tower.created_at %></td>
            <td>
                <a href="<%= topics_path() %>#<%= tower.name.split.join('_').downcase %>" >
                    <button type="button" class="btn btn-success" aria-label="Left Align">
                        view
                    </button>
                </a>
                <a href="<%= edit_tower_path(tower.id) %>" >
                    <button type="button" class="btn btn-info" aria-label="Left Align">
                        edit
                    </button>
                </a>
                <%= link_to raw('<button type="button" class="btn btn-danger" aria-label="Left Align">delete</button>'), tower, method: :delete, data: { confirm: "You sure?" } %>
            </td>

        </tr>
        <% end %>
    </tbody>
   
</table>

<a href="<%= new_tower_path %>" >
    <button type = "button" class = "btn btn-info">Add Tower</button>
</a>

app/views/towers/new.html.erb
<% title "New Tower" %>
<h1 class="text-center">New Tower</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @tower do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control'%>
            <br />
            <%= f.submit "Add", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<table class = "table table-hover">
    <caption>Users List</caption>
   
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Contact</th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.first_name.capitalize %></td>
            <td><%= user.last_name.capitalize %></td>
            <td><%= user.email %></td>
            <td><%= user.contact %></td>
        </tr>
        <% end %>
    </tbody>
   
</table>

app/views/zones/edit.html.erb
<% title "Zone" %>
<h1 class="text-center">Edit Zone</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @zone do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control'%>
            <br />
            <%= f.label :difficulty %>
            <%= f.number_field :difficulty, class: 'form-control'%>
            <br />
            <%= f.label :topic %>
            <br />
            <%= f.collection_select(:topics_id, Topic.all, :id, :name) %>
            <br />
            <br />
            <%= f.hidden_field :topics_id, :value => @topic.id %>
            <%= f.submit "Edit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/zones/show.html.erb
<% title "Questions" %>

<ol class="breadcrumb">
  <li><a href="<%= towers_path %>"><%= @tower.name.upcase %></a></li>
  <li><a href="<%= topic_path(@topic.id) %>"><%= @topic.name.capitalize %></a></li>
  <li class="active"><%= @zone.name %></li>
</ol>

<div class="row">
<div class="col-md-2">
<h1>Questions</h1>
</div>
<div class="col-md-3">
<a href="<%= questions_new_path(:zone_id => @zone.id) %>" >
    <h1 type="button" class="btn btn-success" aria-label="Left Align">add</h1>
</a>
</div>
</div>

<% @questions.each do |question| %>
<div class = "panel panel-default">
    <div data-toggle="collapse" href="#collapse_<%= question.id %>" class = "panel-heading">    
        <%= @count %>: <%= question.question %>
    </div>

    <div id="collapse_<%= question.id %>" class = "panel-collapse collapse">
        <div class="panel-body">
            <ol type="a">
                <li><%= question.a %></li>
                <li><%= question.b %></li>
                <li><%= question.c %></li>
                <li><%= question.d %></li>
            </ol>
            Ans: <%= question.answer %>

            <%= link_to raw('<button type="button" class="btn btn-danger pull-right" aria-label="Left Align">delete</button>'), question, method: :delete, data: { confirm: "You sure?" } %>
            <a class="pull-right" href="<%= edit_question_path(question.id) %>" >
                <button type="button" class="btn btn-info" aria-label="Left Align">
                    edit
                </button>
            </a>
        </div>

        
    </div>
</div>
<% @count += 1 %>
<% end %>