config/routes.rb
Rails.application.routes.draw do
  get 'rankings/index'

  get 'rankings/show'

  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'admin_users/new'

  get 'users', to: 'users#index'
  get 'users/new'

  get 'towers', to: 'towers#index'

  get 'topics', to: 'topics#index'
  post 'topics/new', to: 'topics#create'
  post 'topics/show', to: 'zones#create'

  get 'questions/new'
  post 'questions/new', to: 'questions#create'

  get 'zones/show'

  get 'home', to: 'welcome#index'

  root 'sessions#new'

  resources :admin_users
  resources :zones
  resources :topics
  resources :towers
  resources :questions
  resources :rankings

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/tower.rb
class Tower < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/zone.rb
class Zone < ActiveRecord::Base
end

app/models/zones_question.rb
class ZonesQuestion < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all()

    end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
    def show
        @zone = Zone.find(params['id'])
        @topic = Topic.find(@zone.topics_id)
        @tower = Tower.find(@topic.towers_id)

        @questions = Question.where(zones_id: params['id']).order(id: :asc)
        @count = 1
    end

    def new
    end

    def create
        @topic = Topic.find(zone_params['topic_id'])
        @tower = Tower.find(@topic.towers_id)

        @zone = Zone.new
        @zone.name = zone_params['name'].strip
        @zone.topics_id = zone_params['topic_id']
        @zone.difficulty = zone_params['difficulty']


        if @zone.save!
            flash[:success] = "New tower added successfully!"
            redirect_to topic_path(@topic.id)
        else
            flash[:error] = "Error!"
            redirect_to topic_path(@topic.id)
        end
    end

    def edit
        @zone = Zone.find(params[:id])
        @topic = Topic.find(params[:topic_id])
    end

    def update
         @zone = Zone.find(params[:id])

        if @zone.update_attributes(zone_params)
            flash[:success] = "Edited Zone!"
            redirect_to topic_path(zone_params[:topics_id])
        else
            flash[:error] = "Error!"
            render 'edit'
        end
    end

    def destroy
        topic_id = Zone.find(params[:id]).topic_id
        Zone.find(params[:id]).destroy
        flash[:success] = "Zone deleted"
        redirect_to topic_path(topic_id)
    end

    private
    def zone_params
        params.require(:zone).permit(:name, :difficulty, :topics_id)
    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
    def logged_in_user
        unless logged_in?
            flash[:danger] = "Please log in."
            redirect_to login_url
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(page_title)
        content_for :title, page_title.to_s
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    # Returns the current logged-in user (if any).
    def current_user
        @current_user ||= AdminUser.find_by(id: session[:user_id])
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

      # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "CTC ADMIN", home_path, class: "navbar-brand", id: "logo" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
      <ul class="nav navbar-nav">
        <li><a href="<%= rankings_path %>">Rankings</a></li>
        <li><a href="<%= users_path %>">Users</a></li>
        <li><a href="<%= towers_path %>">Towers</a></li>
        <li><a href="<%= topics_path %>">Topics</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        </li>
      </ul>
      <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CTC Admin | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>